language: java

services:
  - docker
    
before_install:
    - cd docker/dev
    - docker-compose up

script: 
    - mvn clean install -P test-business

notifications:
  email:
    recipients:
      - justine.denoeud@gmail.com
    on_success: never # default: change
    on_failure: always # default: always
