sudo: required

language: java

services:
  - docker
    
before_install:
    - cd docker/dev
    - docker-compose up -d
    - cd ../..

script: 
    - mvn clean install -P test-business
    
after_script:
    - cd docker/dev
    - docker-compose stop

notifications:
  email:
    recipients:
      - justine.denoeud@gmail.com
    on_success: never # default: change
    on_failure: always # default: always
    
#after_success:
#  - bash <(curl -s https://codecov.io/bash)
