sudo: required

language: java

services:
  - docker
    
#before_install:
   # - cd docker/dev
   # - docker-compose up
   # - docker ps -a

script: 
    - docker-compose up
    - mvn clean install -P test-business
    - docker-compose stop

notifications:
  email:
    recipients:
      - justine.denoeud@gmail.com
    on_success: never # default: change
    on_failure: always # default: always
